version: '3'
services:
  web:
    build: .
    ports:
      - "3008:80"
  dev:
    build:
      context: ./dev
    volumes:
      - ./dev:/ansible:ro
    command: ["sh", "-c", "ansible-playbook /ansible/playbook.yml && tail -f /dev/null"]
